name = "beee-media"
compatibility_date = "2024-08-31"

# Pages项目配置
pages_build_output_dir = "."

# 环境变量
[vars]
TIKHUB_API_KEY = "w7MRRTtG50I0nQQRwUXvkCUdwyZXk5mI4alf2QvjknZZ4XIzYNAv/kK8AA=="

# 构建配置
[build]
command = "echo 'Static site ready'"
cwd = "."
watch_dir = "."
